### ISSUE TITLE
`R.callMethod` returns array with some blank elements

### ISSUE THREAD

**Issue by emmansh** [FabrizioSandri/r-integration#8]
If we set up a simple R function that tests each number in an array/vector whether it's larger than 10 and returns Boolean/logical vector.
```r
# in R
is_larger_than_ten <- function(x){
  res <- x > 10
  return(res)
}
```
Then in node:
```javascript
// node js
const R = require('r-integration');
const oneDarray = [3, 8, 12, 14];
let result = R.callMethod("./scripts/is_larger_than_ten.R", "is_larger_than_ten", oneDarray);
console.log(result)
```
We get in the console an array with blanks:
> `[ 'FALSE', 'FALSE', '', 'TRUE', '', 'TRUE' ]`

Which is likely because of the extra spaces when using `print()`:
``` r
v <- c(3, 8, 12, 14)
v > 10
#> [1] FALSE FALSE  TRUE  TRUE
```

**Comment by FabrizioSandri** [comment]
Good catch, there was a missing regExp, just fixed, update to the new version 2.0.0

**Comment by emmansh** [comment]
Thanks! I've updated to 2.0.0 but still getting the same output with blanks...

**Comment by FabrizioSandri** [comment]
I've just checked the execution of your `is_larger_than_ten` function on both Windows and Linux environment. The result is the same after updating `r-integration` to version `2.0.0`:
```js
[ 'FALSE', 'FALSE', 'TRUE', 'TRUE' ]
```

Check that the npm-install command actually updated to the new version `2.0.0`

**Comment by emmansh** [comment]
Hmm it's very strange because I ran and got:
```
$ npm info r-integration version
2.0.0
```

**Comment by FabrizioSandri** [comment]
Released a new version 2.1.0. Now it should be solved, let me know. There was a problem with a regular expression

**Comment by emmansh** [comment]
Thank you for the quick responses! Unfortunately the problem persists :/

**Comment by FabrizioSandri** [comment]
Can you please open the file `node_modules/r-integration/src/R.js` and add at line number 332 the following code:
```js
console.log(Buffer.from(commandResult, 'utf8').toString('hex'));
```

After adding that line, the result will look something like this
```js
...

filterMultiline = (commandResult) => {
    let data;

    console.log(Buffer.from(commandResult, 'utf8').toString('hex'));

...
```

After that can you please execute the script mentioned [here](https://github.com/FabrizioSandri/r-integration/issues/8#issue-1117889723) and provide me the output result? The output should contain a long string of "random" characters, that is the hex representation of the result.

**Comment by emmansh** [comment]
Sure, here it is:
```bash
5b315d2046414c53452046414c53452020545255452020545255450d0a
[ 'FALSE', 'FALSE', '', 'TRUE', '', 'TRUE' ]
```

**Comment by FabrizioSandri** [comment]
I think that the problem is something not correlated to the library itself. I ran tests on Windows and Linux machines and both gave the same correct result.
